name: Code-Runner-From-Issue-1

on:
  issues:
    types: [opened, edited]

run-name: ${{ github.event.issue.title }} ( ${{ github.event.issue.updated_at }} )

jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Create User Name File
      run: echo "${{ github.event.issue.user }}" > name.txt
    - name: Write Python code to file
      run: node WritePythonFile.js
      env:
        PYTHON_CODE: ${{ github.event.issue.body }}
    - name: Set Output Variable
      id: set-output-variable
      run: |
        echo "TempOUTPUT<<EOF
        $(cat output.txt)
        EOF" >> $GITHUB_ENV
    - name: Comment on issue
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        issue-number: ${{ github.event.issue.number }}
        body: |
          <h1>코드 실행 결과</h1>
          <hr>

          ```
          ${{ env.TempOUTPUT }}
          ```
